### ISSUE TITLE
Standardize formatting for state names.

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt-manual-tests#11]
I somehow stumbled over here today and noticed that this repo uses a variety of state names. This includes:

`my_example`, `my-example`, and `/usr/bin/my_example` as opposed to all using `my_example`. If someone gets around to it this should probably be standardized.

**Comment by jfindlay** [comment]
Thanks, @gravyboat.  @jtand, @Ch3LL, and I are using this repo to aid our release testing and development usually happens only when we have to do another release, so it tends to be uneven and impatient, making the title a happy irony (automating manual tests).  I have lots of ideas to expand out here and it's a priority, I just haven't had much time to do it yet.

**Comment by gravyboat** [comment]
Sounds great!
